ialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoialiiasMoiaodels;

class NewExpenseRecurring
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public function __construct(public Expense $expense) {}
}
